# Generated by Django 4.1.7 on 2023-07-21 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonAI', '0002_signup_timestamp_alter_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 14, 23, 25, 368279)),
        ),
    ]
